server:
  port: 8081

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/xgq_exam?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver